# Generated by Django 4.0.3 on 2022-03-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_rename_created_category_created_at_and_more'),
        ('cities', '0002_rename_created_city_created_at_and_more'),
        ('tags', '0003_rename_created_tag_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('place_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('place_lat', models.CharField(max_length=200, verbose_name='Latitud')),
                ('place_long', models.CharField(max_length=200, verbose_name='Longitud')),
                ('place_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('place_approve', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aprovado o Denegado')),
                ('place_state', models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado')),
                ('place_count', models.IntegerField(blank=True, null=True, verbose_name='Contador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('category_id', models.ManyToManyField(blank=True, null=True, to='categories.category', verbose_name='Caregoría')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city', verbose_name='Citiudad')),
                ('tags_id', models.ManyToManyField(blank=True, null=True, to='tags.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
    ]
