# Generated by Django 4.0.3 on 2022-03-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres')),
                ('user_lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('user_password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('user_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('user_photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='photo/', verbose_name='Imagen de perfil')),
                ('user_birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('user_gender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Género')),
                ('user_state', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Usuario App',
                'verbose_name_plural': 'Usuarios App',
            },
        ),
    ]
