# Generated by Django 4.0.3 on 2022-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_state',
            field=models.BooleanField(default=False, verbose_name='Estado de la Etiqueta'),
        ),
    ]
